#!/usr/bin/env bash
set -Eeuo pipefail
trap 'printf "\n\033[31m✗ Endless Sentinel stopped at line %s while running: %s\033[0m\n" "$LINENO" "$BASH_COMMAND" >&2' ERR
GREEN='\033[38;2;0;179;126m'; RED='\033[31m'; YELLOW='\033[33m'; DIM='\033[2m'; RESET='\033[0m'
ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"; INSTALL_DIR="${INSTALL_DIR:-/opt/endless-sentinel}"; ACTION=""; NON_INTERACTIVE=false
banner(){ printf "${GREEN}\n  ╔══════════════════════════════════╗\n  ║       ∞  ENDLESS SENTINEL        ║\n  ║      Homelab Operations Hub      ║\n  ╚══════════════════════════════════╝${RESET}\n\n"; }
info(){ printf "${GREEN}◆${RESET} %s\n" "$*"; }; warn(){ printf "${YELLOW}⚠${RESET} %s\n" "$*"; }; die(){ printf "${RED}✗${RESET} %s\n" "$*" >&2; exit 1; }
usage(){ printf 'Usage: %s [--quick|--advanced|--update|--reconfigure|--status|--logs|--restart|--uninstall] [--install-dir PATH] [--non-interactive]\n' "$0"; }
while (($#)); do case "$1" in --quick|--advanced|--update|--reconfigure|--status|--logs|--restart|--uninstall) ACTION="${1#--}";; --install-dir) shift; INSTALL_DIR="$1";; --non-interactive) NON_INTERACTIVE=true;; --help) usage;exit 0;; *) die "Unknown option: $1";; esac;shift;done
compose(){ if docker compose version >/dev/null 2>&1;then docker compose "$@";else docker-compose "$@";fi; }
check_host(){ command -v docker >/dev/null||die 'Docker is required.'; docker info >/dev/null 2>&1||die 'Docker daemon is unavailable or permission was denied.'; case "$(uname -m)" in x86_64|aarch64|arm64) :;; *) warn "Architecture $(uname -m) is not routinely tested.";; esac; [[ -r /etc/os-release ]]&&. /etc/os-release&&info "Detected ${PRETTY_NAME:-Linux} on $(uname -m)"; }
prompt(){ local var="$1" label="$2" default="$3" secret="${4:-false}" value; if $NON_INTERACTIVE;then printf -v "$var" '%s' "$default";return;fi; if [[ "$secret" == true ]];then read -r -s -p "$label: " value;printf '\n';else read -r -p "$label [$default]: " value;fi;printf -v "$var" '%s' "${value:-$default}"; }
yesno(){ local label="$1" default="${2:-false}" ans;if $NON_INTERACTIVE;then [[ "$default" == true ]];return;fi;read -r -p "$label [y/N]: " ans;[[ "${ans,,}" == y || "${ans,,}" == yes ]]; }
hash_password(){ python3 -c 'from werkzeug.security import generate_password_hash;import getpass;print(generate_password_hash(getpass.getpass("Administrator password: ")))' ; }
setkv(){ local file="$1" key="$2" value="$3" tmp="${file}.tmp";awk -v k="$key" -v v="$value" 'BEGIN{done=0} $0~("^"k"="){print k"="v;done=1;next}{print} END{if(!done)print k"="v}' "$file" > "$tmp";chmod 600 "$tmp";mv "$tmp" "$file"; }
prepare_files(){ mkdir -p "$INSTALL_DIR";if [[ "$ROOT_DIR" != "$INSTALL_DIR" ]];then cp -a "$ROOT_DIR"/. "$INSTALL_DIR"/;fi;cd "$INSTALL_DIR";[[ -f .env ]]||{ cp .env.example .env;chmod 600 .env; }; }
configure(){ local advanced="${1:-false}" env="$INSTALL_DIR/.env";[[ -f "$env" ]]||cp "$INSTALL_DIR/.env.example" "$env";if [[ -f "$env" ]];then cp -a "$env" "${env}.backup.$(date +%Y%m%d%H%M%S)";fi
  prompt ADMIN_USER 'Administrator username' "${ADMIN_USERNAME:-admin}";setkv "$env" ADMIN_USERNAME "$ADMIN_USER"
  if ! $NON_INTERACTIVE;then local HASH;HASH="$(hash_password)";setkv "$env" ADMIN_PASSWORD_HASH "$HASH";elif ! grep -q '^ADMIN_PASSWORD_HASH=.' "$env";then die 'Non-interactive first install requires ADMIN_PASSWORD_HASH in the environment or existing .env.';fi
  local SECRET;SECRET="$(python3 -c 'import secrets;print(secrets.token_urlsafe(48))')";grep -q '^APP_SECRET_KEY=.' "$env"||setkv "$env" APP_SECRET_KEY "$SECRET"
  if [[ "$advanced" == true ]];then
    prompt WEB_PORT_VALUE 'Dashboard port' '8080';setkv "$env" WEB_PORT "$WEB_PORT_VALUE";prompt POLL 'Polling interval seconds' '30';setkv "$env" POLL_INTERVAL_SECONDS "$POLL"
    prompt CPUW 'CPU warning percent' '80';prompt CPUC 'CPU critical percent' '95';prompt RAMW 'RAM warning percent' '80';prompt RAMC 'RAM critical percent' '95';setkv "$env" CPU_WARNING_PERCENT "$CPUW";setkv "$env" CPU_CRITICAL_PERCENT "$CPUC";setkv "$env" RAM_WARNING_PERCENT "$RAMW";setkv "$env" RAM_CRITICAL_PERCENT "$RAMC"
    yesno 'Use secure session cookies (HTTPS required)?' false&&setkv "$env" SESSION_COOKIE_SECURE true||setkv "$env" SESSION_COOKIE_SECURE false;prompt TRUST 'Trusted reverse proxy count' '0';setkv "$env" TRUST_PROXY_COUNT "$TRUST"
    configure_integrations "$env";configure_webhooks "$env";prompt LM 'Login attempts per minute' '5';prompt LH 'Login attempts per hour' '20';prompt AC 'Operational alert cooldown seconds' '900';prompt SC 'Security alert cooldown seconds' '900';setkv "$env" LOGIN_RATE_LIMIT_MINUTE "$LM";setkv "$env" LOGIN_RATE_LIMIT_HOUR "$LH";setkv "$env" ALERT_COOLDOWN_SECONDS "$AC";setkv "$env" SECURITY_ALERT_COOLDOWN_SECONDS "$SC"
  fi;chmod 600 "$env";if [[ ${EUID:-$(id -u)} -eq 0 ]];then chown 10001:10001 "$env";fi; }
configure_integrations(){ local env="$1";if yesno 'Enable Proxmox monitoring?' false;then setkv "$env" PROXMOX_ENABLED true;prompt PH 'Proxmox host' '';prompt PU 'API user' '';prompt PN 'Token name' '';prompt PV 'Token value' '' true;setkv "$env" PROXMOX_HOST "$PH";setkv "$env" PROXMOX_USER "$PU";setkv "$env" PROXMOX_TOKEN_NAME "$PN";setkv "$env" PROXMOX_TOKEN_VALUE "$PV";yesno 'Verify Proxmox TLS?' true&&setkv "$env" PROXMOX_VERIFY_SSL true||setkv "$env" PROXMOX_VERIFY_SSL false;else setkv "$env" PROXMOX_ENABLED false;fi
  if yesno 'Enable Kubernetes/k3s monitoring?' false;then setkv "$env" K3S_ENABLED true;prompt KP 'Kubeconfig path' '/config/kubeconfig';prompt KC 'Kubernetes context (optional)' '';setkv "$env" KUBECONFIG_PATH "$KP";setkv "$env" K3S_CONTEXT "$KC";else setkv "$env" K3S_ENABLED false;fi
  if yesno 'Enable Docker monitoring?' false;then setkv "$env" DOCKER_ENABLED true;prompt DH 'Docker endpoint' 'unix:///var/run/docker.sock';setkv "$env" DOCKER_HOST "$DH";else setkv "$env" DOCKER_ENABLED false;fi; }
configure_webhooks(){ local env="$1" OP SEC;prompt OP 'Operational Discord webhook (optional)' '' true;prompt SEC 'Security Discord webhook (optional, must differ)' '' true;if [[ -n "$OP" && "$OP" == "$SEC" ]];then warn 'The webhook URLs are identical; security webhook was not saved.';SEC='';fi;setkv "$env" DISCORD_WEBHOOK_URL "$OP";setkv "$env" SECURITY_DISCORD_WEBHOOK_URL "$SEC"; }
install_app(){ local advanced="${1:-false}";check_host;prepare_files;configure "$advanced";info 'Building and starting the service';compose up -d --build;summary; }
summary(){ cd "$INSTALL_DIR";local port;port="$(sed -n 's/^WEB_PORT=//p' .env|tail -1)";port="${port:-8080}";info 'Installation complete';printf '  Dashboard: http://%s:%s\n' "$(hostname -I 2>/dev/null|awk '{print $1}'||printf localhost)" "$port";compose ps;printf '\n  Status:  cd %q && docker compose ps\n  Logs:    cd %q && docker compose logs -f\n  Restart: cd %q && docker compose restart\n  Update:  %q --update --install-dir %q\n' "$INSTALL_DIR" "$INSTALL_DIR" "$INSTALL_DIR" "$0" "$INSTALL_DIR";grep -E '^(PROXMOX|K3S|DOCKER)_ENABLED=' .env|sed 's/^/  /'; }
menu(){ if command -v whiptail >/dev/null;then ACTION="$(whiptail --title 'Endless Sentinel' --menu 'Choose an action' 20 70 10 quick 'Quick install with Docker Compose' advanced 'Advanced install' update 'Update existing installation' reconfigure 'Reconfigure integrations and credentials' status 'View status' logs 'View recent logs' restart 'Restart service' uninstall 'Uninstall' 3>&1 1>&2 2>&3)"||exit 0;else printf '1) Quick install  2) Advanced  3) Update  4) Reconfigure\n5) Status  6) Logs  7) Restart  8) Uninstall\n';read -r -p 'Selection: ' n;ACTION="$(printf '%s\n' quick advanced update reconfigure status logs restart uninstall|sed -n "${n}p")";fi; }
banner;[[ -n "$ACTION" ]]||menu
case "$ACTION" in quick)install_app false;;advanced)install_app true;;update)check_host;prepare_files;compose pull||warn 'No remote image update available; rebuilding local source.';compose up -d --build;summary;;reconfigure)prepare_files;configure true;compose up -d --force-recreate;summary;;status)cd "$INSTALL_DIR";compose ps;;logs)cd "$INSTALL_DIR";compose logs --tail=100;;restart)cd "$INSTALL_DIR";compose restart;compose ps;;uninstall)cd "$INSTALL_DIR";yesno 'Stop and remove Endless Sentinel?' false||exit 0;compose down;if yesno 'Preserve configuration and application data?' true;then info "Configuration preserved in $INSTALL_DIR";else [[ "$INSTALL_DIR" == /opt/endless-sentinel ]]||die 'Refusing to remove a non-default directory automatically.';rm -rf --one-file-system /opt/endless-sentinel;info 'Application and configuration removed.';fi;;*)usage;exit 1;;esac
